drop table parametry_reguly if exists;

drop table reguly if exists;

drop table wywolania_regul if exists;

drop table parametry_wywolania_regul if exists;




CREATE TABLE IF NOT EXISTS reguly (
   id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1),
   kod VARCHAR (45),
   tresc VARCHAR(500),
   wersja INTEGER

)

create TABLE IF NOT EXISTS parametry_reguly(
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1),
	regula_id int ,
	nazwa VARCHAR (45),
	typ VARCHAR (45),
	wartosc_domyslna VARCHAR (150),
	wersja INTEGER,
	 FOREIGN KEY (regula_id)  REFERENCES reguly(id)
	)


 create TABLE IF NOT EXISTS wywolania_regul(
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1),
	regula_wolajaca_id int ,
	regula_wolana_id int ,
	FOREIGN KEY (regula_wolajaca_id)  REFERENCES reguly(id),
	FOREIGN KEY (regula_wolana_id)  REFERENCES reguly(id)
	)

 create TABLE IF NOT EXISTS parametry_wywolania_regul(
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1),
	wywolanie_id int ,
	nazwa_parametru_reg_wolajaca VARCHAR (45) ,
	nazwa_parametru_reg_wolana VARCHAR (45) ,
	FOREIGN KEY (wywolanie_id)  REFERENCES wywolania_regul(id)
	)
