drop table parametry_reguly;

drop table reguly;

CREATE TABLE IF NOT EXISTS reguly (
   id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1),
   kod VARCHAR (45) UNIQUE,
   tresc VARCHAR(500),
   wersja INTEGER

)
;
create TABLE IF NOT EXISTS parametry_reguly(
	 id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1),
	regula_id int ,
	nazwa VARCHAR (45),
	typ VARCHAR (45),
	wartosc_domyslna VARCHAR (150),
	wersja INTEGER,
	 FOREIGN KEY (regula_id)  REFERENCES reguly(id)
	)
;